### PR TITLE
Fix tests, resin-lint, add missing typings

### PR DESCRIPTION
**Pull request by zvin**
---- Autogenerated Waffleboard Connection: Connects to #24

### CODE REVIEW

**Comment by dfunckt** [comment]
This module is used in the cli and requiring es2017 means users will only be able to use the cli with node 8 on their computers.

**Comment by dfunckt** [comment]
Though I see now you’re not using any of its features so it should be good to go as a whole, but let’s please revert the TS target to es6

**Comment by zvin** [comment]
>Though I see now you’re not using any of its features so it should be good to go as a whole, but let’s please revert the TS target to es6

@dfunckt reverted to es6

**Comment by roman-mazur** [comment]
@zvin how actual is this PR?
What parts hasn't been addressed?

**Comment by zvin** [comment]
@roman-mazur this is old. I guess we can close it.

**Pull request closed without merging**
